#!/bin/bash

#images='/usr/local/share/backgrounds'
images='/home/shgn/Pictures/back'

cnt=$(ls $images/*.png | wc -l)
randnum=$((RANDOM%$cnt+1))
background=$(ls $images/*.png | sed -n "${randnum}p")

i3lock -i $background
